### PR TITLE
[c2cpg] Fixed MethodRef typeFullName

### PR DESCRIPTION
**Pull request by max-leuthaeuser**

### CODE REVIEW

**Review by johannescoetzee — COMMENTED** [review]
Could you add a unit test for this, or is it a difficult-to-test case?

**Comment by max-leuthaeuser** [comment]
It happened during some new sptests projects I am working one and I did not yet find a minimal reproducing example. Will update this PR. 
Consider it as WIP for now. You do not need to review yet - sorry for the ping.

**Comment by johannescoetzee** [comment]
Sounds good! Just ping me on slack when it's ready (although the changes so far look fine)

**Comment by max-leuthaeuser** [comment]
The changes in this PR have been validated with https://github.com/ShiftLeftSecurity/codescience/pull/7730
They are surely not covering all the C++ edge cases with fullnames right now but at least we can now run the full c2cpg -> cpg2sp chain without crashes.
I will use these results to gradually enhance the unit tests here in joern afterwards.

**Review by johannescoetzee — APPROVED** [review]

**Pull request merged**
