### PR TITLE
Delete Plume Related Code and Introduce jimple2cpg

### PR DESCRIPTION
**Pull request by DavidBakerEffendi**
So most of what I could find of Plume I removed but I think there might be an additional step left in `codepropertygraph` or this project to fully integrate this.

### CODE REVIEW

**Comment by mpollmeier** [comment]
fyi i just pushed c63714e to your branch

**Comment by mpollmeier** [comment]
what might be missing is to update https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/console/src/main/scala/io/shiftleft/console/cpgcreation/JavaCpgGenerator.scala, or is joern-parse still the correct thing to invoke here?

**Comment by mpollmeier** [comment]
something's odd when i try and use jimple2cpg - i tested 2 ways, my jar is 30m. 
prereq: `sbt clean stage`

1) 
```
./joern
`importCode.java("some.jar")`
```
calls joern-parse, which doesn't ever seem to finish, keeps my cpus busy and memory grows until it's killed... 
meanwhile, log output is empty. 

2) 
```
cd joern-cli/target/universal/stage/
./jimple2cpg some.jar
```
prints a few warnings about missing slf4j bindings and then exits, leaving behind a 12k cpg.bin which looks like an overflowdb binary, albeit it seems to be empty (only judging by it's size)

**Comment by DavidBakerEffendi** [comment]
I think there must be an issue in the JAR unpacking - perhaps unpacking it to the target directory is causing a recursive re-execution of classes or something. I'll see if unpacking the JAR to a temporary directory will fix this.

**Comment by DavidBakerEffendi** [comment]
> https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/console/src/main/scala/io/shiftleft/console/cpgcreation/JavaCpgGenerator.scala

This might be the next thing to change

**Comment by DavidBakerEffendi** [comment]
> something's odd when i try and use jimple2cpg - i tested 2 ways, my jar is 30m.
> prereq: `sbt clean stage`
> 
> 
> ```
> ./joern
> `importCode.java("some.jar")`
> ```
> 
> calls joern-parse, which doesn't ever seem to finish, keeps my cpus busy and memory grows until it's killed...
> meanwhile, log output is empty.
> 
> 
> ```
> cd joern-cli/target/universal/stage/
> ./jimple2cpg some.jar
> ```
> 
> prints a few warnings about missing slf4j bindings and then exits, leaving behind a 12k cpg.bin which looks like an overflowdb binary, albeit it seems to be empty (only judging by it's size)

I have fixed number 2 in jimple2cpg 0.0.4 - now to find out the way to connect it with Joern

**Comment by DavidBakerEffendi** [comment]
@mpollmeier PR in `codepropertygraph` now looks for jimple2cpg https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1408

**Comment by mpollmeier** [comment]
This works fine, and generates a cpg, albeit it's pretty empty...

```
joern> cpg.graph
res1: Graph = Graph [407 nodes]

joern> cpg.meth
method        methodRef     methodReturn
joern> cpg.method.name.l
res2: List[String] = List()
```

**Comment by DavidBakerEffendi** [comment]
Mind pointing me to the JAR you're testing to validate the output?

**Comment by mpollmeier** [comment]
I tested with something internal, but you get the same results with https://github.com/ShiftLeftSecurity/HelloShiftLeft

Here's a few things i tried:
```
git clone https://github.com/ShiftLeftSecurity/HelloShiftLeft.git
cd HelloShiftLeft
mvn clean package

./joern
importCode.java("/home/mp/tmp/hsl-public/HelloShiftLeft/target/hello-shiftleft-0.0.1.jar")

cpg.graph
// Graph [396 nodes]

joern> cpg.method.count.head
// 0

cpg.graph.nodes.label.groupCount.l
res10: List[(String, Int)] = List(
  ("NAMESPACE_BLOCK", 77),
  ("TYPE_DECL", 77),
  ("NAMESPACE", 11),
  ("META_DATA", 1),
  ("FILE", 153),
  ("TYPE", 77)
)


```

**Comment by DavidBakerEffendi** [comment]
> I tested with something internal, but you get the same results with https://github.com/ShiftLeftSecurity/HelloShiftLeft
> 
> Here's a few things i tried:
> 
> ```
> git clone https://github.com/ShiftLeftSecurity/HelloShiftLeft.git
> cd HelloShiftLeft
> mvn clean package
> 
> ./joern
> importCode.java("/home/mp/tmp/hsl-public/HelloShiftLeft/target/hello-shiftleft-0.0.1.jar")
> 
> cpg.graph
> // Graph [396 nodes]
> 
> joern> cpg.method.count.head
> // 0
> 
> cpg.graph.nodes.label.groupCount.l
> res10: List[(String, Int)] = List(
>   ("NAMESPACE_BLOCK", 77),
>   ("TYPE_DECL", 77),
>   ("NAMESPACE", 11),
>   ("META_DATA", 1),
>   ("FILE", 153),
>   ("TYPE", 77)
> )
> ```

Fixed it in v0.0.5 but SonaType has taken forever now - hopefully this will be up by tomorrow

**Comment by DavidBakerEffendi** [comment]
Just checked and it seems everything is working, just need a confirmation and merge @mpollmeier

**Comment by mpollmeier** [comment]
thanks @DavidBakerEffendi , will bring in https://github.com/joernio/joern/pull/609 first and then test everything together and merge

**Comment by mpollmeier** [comment]
frontend works just fine, we just need to wire up the slf4j logging correctly - i'll see what i can do

**Comment by DavidBakerEffendi** [comment]
> frontend works just fine, we just need to wire up the slf4j logging correctly - i'll see what i can do

I think the logging issue may be a Soot-related as that is the only difference between, say JavaSrc2Cpg, is that one uses JavaParser and one uses Soot.

**Comment by mpollmeier** [comment]
I added an slf4j bindings so the warnings about "no slf4j binding available" disappear. 
That being said, it doesn't look like jimple writes many log entries, be it info/success messages or error e.g. if I pass it a file it can't handle. 
But I guess that's a separate issue from this jimple/joern integration, wdyt @DavidBakerEffendi ?

**Review by mpollmeier — APPROVED** [review]

**Comment by DavidBakerEffendi** [comment]
> I added an slf4j bindings so the warnings about "no slf4j binding available" disappear.
> That being said, it doesn't look like jimple writes many log entries, be it info/success messages or error e.g. if I pass it a file it can't handle.
> But I guess that's a separate issue from this jimple/joern integration, wdyt @DavidBakerEffendi ?

Yeah I can make an issue for it and we can handle it as a separate bug?

**Pull request merged**
