### PR TITLE
change packaging: download frontends as binaries

### PR DESCRIPTION
**Pull request by mpollmeier**
* also: upgrade cpg

### reasons to invoke frontends via shell command rather than jvm dependency
* smaller classpath
  * sbt/idea/... work faster
  * joern/ocular start faster
* no hidden memory leaks (as observed with fuzzyc2cpg)
* less complexity in classpath
* no issues with jre versions
* only a matter of time until we have version clashes between frontends

### CODE REVIEW

**Review by ursachec — APPROVED** [review]

**Comment by johannescoetzee** [comment]
It looks like with the current revision, `sbt stage` is no longer sufficient to get a working joern build from a clean repo. Would it be possible to add fetch and extract steps as part of the stage job?

**Comment by mpollmeier** [comment]
yes, good point, I'll take a look

**Comment by mpollmeier** [comment]
@johannescoetzee done, stage and distribution now work
will test `joern-install.sh` again after this was merged/released

**Review by johannescoetzee — APPROVED** [review]
Looks like everything is working as expected!

**Pull request merged**
