### PR TITLE
jssrc2cpg: set type hints for locals and identifiers based on imports

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
Replaces: https://github.com/joernio/joern/pull/1780

### CODE REVIEW

**Review by maltek — CHANGES_REQUESTED** [review]
Either we set dynamic type hints to proper carrot paths (`^module-name^.member`) or we find a way to avoid it (i.e. generate some intermediate field accesses). But let's not set dynamic type hints to some incompatible values.

**Comment by max-leuthaeuser** [comment]
Isnt that what Markus mentioned (https://github.com/ShiftLeftSecurity/codescience/blob/5e44e1389d128c5a21431f14f191515fd6c29312/dataflowengine/src/main/scala/io/shiftleft/dataflowengine/passes/languagespecific/javascript/ExportTypeDeclCreator.scala#L273)?

**Comment by maltek** [comment]
Ugh, I was only thinking about imports of external modules. That code is creating types for exported objects in the CPG. The two cases use incompatible naming schemes (avoiding collisions). For external libraries, we need carrot-paths (`^module-name^.member`). For internal it would currently need to be something like `./cpg/file/name.member` (but that one we're free to change as long as we change `ExportTypeDeclCreator` in lock-step).

**Comment by max-leuthaeuser** [comment]
Closed in favor of: https://github.com/joernio/joern/pull/1780

**Pull request closed without merging**
