### PR TITLE
Added null/ to .gitignore

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
This is some Coursier cache folder.

### CODE REVIEW

**Comment by mpollmeier** [comment]
i don't have that... are you sure? how can i reproduce?

**Comment by max-leuthaeuser** [comment]
Run sbt compile or test. Maybe it's a Windows related issue.

**Comment by max-leuthaeuser** [comment]
See: https://github.com/sbt/sbt/issues/5206
Well.. Don't know exactly how to solve this issue.

**Comment by max-leuthaeuser** [comment]
Ok, got it. It only happens on Windows after upgrading SBT.
So for future readers:
1) update SBT
2) run compile or test at least once
3) manually delete the `null/` folder created by SBT/Coursier.
4) run compile or test and notice that no new `null/` folder will be created.

**Comment by mpollmeier** [comment]
Thanks for digging into this, good to know!
Btw I don't mind having `null/` in our gitignore, I just wanted to understand where this is coming from.

**Review by mpollmeier — APPROVED** [review]

**Pull request merged**
