### PR TITLE
Add js2cpg and javasrc2cpg to updateDependencies and bump versions

### PR DESCRIPTION
**Pull request by johannescoetzee**
# Testing
Bumped versions with `./updateDependencies.sh`
`sbt clean test stage`

### CODE REVIEW

**Review by mpollmeier — APPROVED** [review]

**Comment by johannescoetzee** [comment]
I'm holding off on merging this till the PR checks pass. It looks like JitPack is down at the moment, causing the Plume fetch failures.

**Comment by mpollmeier** [comment]
JitPack behaves a little strange for newly deployed artifacts, it seems to only work on the second try, at least that was my experience last time...
Plume will shortly be replaced by jimple2cpg, which is deployed to sonatype, so for now workarounds are fine. 
cc @DavidBakerEffendi

**Comment by mpollmeier** [comment]
I just restarted the build and have a feeling that things will magically improve

**Comment by johannescoetzee** [comment]
I have no idea how reliable this site is, but https://www.saashub.com/jitpack-status seems to agree that it should be fine now

**Pull request merged**
