### PR TITLE
github actions: use jdk21 (LTS)

### PR DESCRIPTION
**Pull request by mpollmeier**

### CODE REVIEW

**Comment by DavidBakerEffendi** [comment]
Looks like the ASM used by Soot doesn't like JDK21. While I have this upgrade branch https://github.com/joernio/joern/tree/dave/jimple/sootup-upgrade, I wonder if we can force an upgrade on ASM in the meantime

**Comment by mpollmeier** [comment]
I just upgraded asm for jimple - let's see what ci says

**Comment by mpollmeier** [comment]
locally it's green :)

**Comment by DavidBakerEffendi** [comment]
Hopefully this PR will help the `jimple2cpg` related issues here: https://github.com/joernio/joern/pull/4497

**Review by DavidBakerEffendi — APPROVED** [review]

**Pull request merged**
