### PR TITLE
Publish test artifacts for all projects.

### PR DESCRIPTION
**Pull request by ml86**
Some of the code we have under tests is or will be reused in other
projects. Mainly our test fixtures will be reused but creating
individual projects which just test utilities for each already existing
project seem overkill.

### CODE REVIEW

**Comment by Liyw979** [comment]
Thanks for this

**Review by mpollmeier — APPROVED** [review]
as discussed on slack

just checked: the kotlin2cpg-tests jar is 4M, since it contains some jars... if the release job slows down significantly by this change, we should externalise those jars and potentially reconcider this change, and instead whitelist project by project

**Comment by ml86** [comment]
I missed that. For now the 4MB will not hurt us much. But i will take a look and try to get rid of those jars.

**Comment by mpollmeier** [comment]
looks like release runtimes haven't changed
https://github.com/joernio/joern/actions/workflows/release.yml

**Pull request merged**
