### PR TITLE
jssrc2cpg: multiple fixes for crashes in ts-parser-test-ref

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
While working on support for stuff from https://github.com/swc-project/ts-parser-test-ref I stumpled uppon multiple crashes. This PR fixes them with:

- fix for TS binding patterns (we need to handle ObjectProperty without a member name)
- fix for TS constructor parameter assignments
- fix for exported variable with array declaration

### CODE REVIEW

**Comment by max-leuthaeuser** [comment]
@mpollmeier There is still something wrong with `tests/frontends-smoketest.sc`
It crashes repeatable: https://github.com/joernio/joern/actions/runs/5654536667/job/15318174222?pr=3225

**Comment by mpollmeier** [comment]
That flakeyness is a duplicate of https://github.com/joernio/joern/issues/3087 and unfortunately it doesn't always crash and isn't locally reproducable - at least for david and me :(

**Comment by max-leuthaeuser** [comment]
Yes, and it did the trick.

**Comment by xavierpinho** [comment]
🤷‍♂️

**Pull request closed without merging**
