### PR TITLE
Joern Benchmark Project

### PR DESCRIPTION
**Pull request by DavidBakerEffendi**
- Added a new subproject called `benchmarks`
- The idea is that we can formally measure the performance of various metrics (e.g. building CPG speed, taint analysis precision, etc.) using commonly used benchmarks.
- For now, have simply added Securibench Micro for Java/JVM frontends.
- The project is driven using `scalatest`
- Benchmarks create a markdown table with the results for each category as below:
- Added `joern-benchmarks` script to run benchmarks and update `benchmarks/README.md` with the results

#### Java Source Results

| Category          | #    | FP   | TP   | TN   | FN   |
| ----------------- | ---- | ---- | ---- | ---- | ---- |
| Aliasing          | 14 | 1 | 4 | 1 | 8 |
| Arrays            | 15 | 4 | 7 | 2 | 2 |
| Basic             | 67 | 5 | 59 | 1 | 2 |
| Collections       | 22 | 8 | 14 | 0 | 0 |
| Data Structures   | 8 | 1 | 2 | 2 | 3 |
| Factories         | 6 | 3 | 3 | 0 | 0 |
| Inter-procedural  | 25 | 7 | 8 | 3 | 7 |
| Predicates        | 9 | 4 | 5 | 0 | 0 |
| Reflection        | 4 | 1 | 1 | 0 | 2 |
| Sanitizers        | 9 | 3 | 2 | 2 | 2 |
| Session           | 4 | 1 | 3 | 0 | 0 |
| Strong Updates    | 5 | 0 | 0 | 4 | 1 |
| *Total*           | *188* | *38* | *108* | *15* | *27* |

Total accuracy: 65,426%

#### JVM Bytecode Results

| Category          | #    | FP   | TP   | TN   | FN   |
| ----------------- | ---- | ---- | ---- | ---- | ---- |
| Aliasing          | 14 | 1 | 10 | 1 | 2 |
| Arrays            | 15 | 5 | 7 | 1 | 2 |
| Basic             | 67 | 5 | 60 | 1 | 1 |
| Collections       | 22 | 8 | 14 | 0 | 0 |
| Data Structures   | 8 | 1 | 2 | 2 | 3 |
| Factories         | 6 | 3 | 3 | 0 | 0 |
| Inter-procedural  | 25 | 5 | 7 | 5 | 8 |
| Predicates        | 9 | 3 | 5 | 1 | 0 |
| Reflection        | 4 | 1 | 2 | 0 | 1 |
| Sanitizers        | 9 | 3 | 2 | 2 | 2 |
| Session           | 4 | 1 | 3 | 0 | 0 |
| Strong Updates    | 5 | 0 | 0 | 4 | 1 |
| *Total*           | *188* | *36* | *115* | *17* | *20* |

Total accuracy: 70,213%

### CODE REVIEW

**Comment by DavidBakerEffendi** [comment]
The idea with this PR is just to get the framework started and approved with this example benchmark. I plan to add more in the near future for less bias for the kinds of skewing of categories that happens in some datasets.

**Review by mpollmeier — APPROVED** [review]

**Review by fabsx00 — COMMENTED** [review]
I wonder: do we need to check in the class files here or should we build them on demand when people run the benchmark? Also, we're running this benchmark on-demand only, right?

**Comment by DavidBakerEffendi** [comment]
> I wonder: do we need to check in the class files here or should we build them on demand when people run the benchmark? Also, we're running this benchmark on-demand only, right?

We can, but Securibench for example requires these libraries: https://github.com/too4words/securibench-micro/tree/master/lib which we'll need to add. In the long run it may cost less storage.

**Comment by mpollmeier** [comment]
> Also, we're running this benchmark on-demand only, right?

that should be fine, he added a root project that aggregates all subproject except benchmarks to the `/build.sbt`

**Pull request merged**
