### PR TITLE
Introduce `HasStoreAndPersistMethods` trait

### PR DESCRIPTION
**Pull request by claudiuvursache**
helper trait to ease the switch to the new DiffGraph API

### CODE REVIEW

**Comment by bbrehm** [comment]
I'm against this way of changing it. The coding pattern of using an implicit builder and then hitting ".store()" on a node is imo terrible. Furthermore, `tagNodePair` is an abomination. This is not a node in the graph; somebody added it to the schema to make the "DSL" more pretty.

It is a nice side-effect of the migration that we can get rid of that cruft. It is a further nice side-effect that we get to fix lots and lots of bugs in old code because someone looks at it with new eyes.

**Comment by claudiuvursache** [comment]
@bbrehm i'm with you in that it's not ideal, and it may well be we can find better alternatives, at the moment my goal is to get rid of the deprecated DiffGraph API usage and for that, the change is very well suited.

**Comment by bbrehm** [comment]
We removed almost all other deprecated DiffGraph API usage without porting cruft. The `.store()` function will get deprecated next, and it makes imo no sense to do the work twice. When we change the API on a fundamental level, then we should also do the necessary refactoring of coding patterns.

**Comment by claudiuvursache** [comment]
discussed offline, we'll go with the change as it is for now

**Pull request merged**
