### PR TITLE
kotlin2cpg: use string interpolation instead of +

### PR DESCRIPTION
**Pull request by claudiuvursache**
one-liner to find spots using it
```
grep '[^"]*"[^"]*"[^+]+' -R joern-cli/frontends/kotlin2cpg/src/main -n -I
```

### CODE REVIEW

**Review by johannescoetzee — APPROVED** [review]
The regex in the description is truly a thing of beauty :)

**Review by mpollmeier — APPROVED** [review]
👏🏻 for the regex 😸

**Review by max-leuthaeuser — APPROVED** [review]

**Comment by claudiuvursache** [comment]
lol, glad you like it

**Comment by max-leuthaeuser** [comment]
👍 
(Could be done for all frontends in a seperate PR :-) )

**Comment by claudiuvursache** [comment]
@max-leuthaeuser yesss, for sure, i intend to do cleanups in the other frontends as well as soon as kotlin2cpg is a bit cleaner and more maintainable than it currently is ; )

**Pull request merged**
