### PR TITLE
Change python instance class type full names.

### PR DESCRIPTION
**Pull request by ml86**
So far the full name for the instance class type of:
```
class Foo:
  pass
```

was `fileName.py:<module>.Foo.Foo`. This is now changed to:
`fileName.py:<module>.Foo`.

C.f.: https://github.com/joernio/joern/issues/2225

### CODE REVIEW

**Comment by ml86** [comment]
@DavidBakerEffendi I will need your help here. The type recovery does a tone of type/method name parsing and only seems to have tests for the type recovery end results but not the individual parsing functions. So i would need to read through this hole thing in order to debug and fix.

**Comment by DavidBakerEffendi** [comment]
@ml86 [This PR](https://github.com/joernio/joern/pull/2370) passes the tests for type recovery

**Comment by DavidBakerEffendi** [comment]
@ml86 Seems like some other tests are failing
```
[info] ClassCpgTests:
[3270](https://github.com/joernio/joern/actions/runs/4404027533/jobs/7713121839#step:5:3271)
[info] class
[3271](https://github.com/joernio/joern/actions/runs/4404027533/jobs/7713121839#step:5:3272)
[info] - should have correct instance class type and typeDecl
[3272](https://github.com/joernio/joern/actions/runs/4404027533/jobs/7713121839#step:5:3273)
[info] - should have correct meta class type and typeDecl
[3273](https://github.com/joernio/joern/actions/runs/4404027533/jobs/7713121839#step:5:3274)
[info] - should have correct class body type and typeDecl *** FAILED ***
[3274](https://github.com/joernio/joern/actions/runs/4404027533/jobs/7713121839#step:5:3275)
[info]   io.shiftleft.codepropertygraph.generated.nodes.Method[label=METHOD; id=15] was not equal to io.shiftleft.codepropertygraph.generated.nodes.TypeDecl[label=TYPE_DECL; id=11] (ClassCpgTests.scala:29)
[3275](https://github.com/joernio/joern/actions/runs/4404027533/jobs/7713121839#step:5:3276)
[info] - should have correct meta class call handler type and typeDecl *** FAILED ***
[3276](https://github.com/joernio/joern/actions/runs/4404027533/jobs/7713121839#step:5:3277)
[info]   io.shiftleft.codepropertygraph.generated.nodes.Method[label=METHOD; id=23] was not equal to io.shiftleft.codepropertygraph.generated.nodes.TypeDecl[label=TYPE_DECL; id=11] (ClassCpgTests.scala:37)
[3277](https://github.com/joernio/joern/actions/runs/4404027533/jobs/7713121839#step:5:3278)
[info] - should have correct fake new type and typeDecl *** FAILED ***
[3278](https://github.com/joernio/joern/actions/runs/4404027533/jobs/7713121839#step:5:3279)
[info]   io.shiftleft.codepropertygraph.generated.nodes.Method[label=METHOD; id=37] was not equal to io.shiftleft.codepropertygraph.generated.nodes.TypeDecl[label=TYPE_DECL; id=11] (ClassCpgTests.scala:45)
```

**Comment by ml86** [comment]
This may take a while. I cannot reproduce locally and will now try to `printf` debug this remotely via github actions. Can you reproduce locally?

**Comment by ml86** [comment]
Wow, apparently our PR tests run against a rebased version of the PR branches, were the PR branch was rebased onto master...
If that is not unintuitive, i dont know what is.

**Pull request merged**
