### PR TITLE
use newc frontend instead of oldc in CQueryTestSuite

### PR DESCRIPTION
**Pull request by raymontag**
Fix for #758

### CODE REVIEW

**Review by fabsx00 — APPROVED** [review]

**Comment by raymontag** [comment]
I noticed, that for the failing tests a `.whereNot(_.name("<global>"))` in the query does fix it but I guess it would be better to modify the test cases?

**Comment by max-leuthaeuser** [comment]
> I noticed, that for the failing tests a `.whereNot(_.name("<global>"))` in the query does fix it but I guess it would be better to modify the test cases?

I guess a `.nameNot("<global>")` is ok. Lets wait for @fabsx00 answer.

**Comment by fabsx00** [comment]
Yes, that should be ok, please go ahead.

**Comment by raymontag** [comment]
I added a fix in the PR

**Comment by max-leuthaeuser** [comment]
> I added a fix in the PR

This needs some `scalafmt`.

**Pull request merged**
