### PR TITLE
WIP add (failing) test to verify that two calls are part of the DDG

### PR DESCRIPTION
**Pull request by mpollmeier**
I'm not the best person to judge wether those calls really _should_
be part of the DDG, but from our discussion on
[discord](https://discord.com/channels/832209896089976854/832209896089976857/1044687371800678420)
it sounds like the answer is 'yes'.
Anywhere, since I was asked about this I just added a (failing) test
to hopefully make it easier to grok the context and take it from
there.

### CODE REVIEW

**Comment by max-leuthaeuser** [comment]
Thanks! I also asked @bbrehm about this.

**Comment by mpollmeier** [comment]
fwiw here's the dot graph:

ddg-minified

[ddg-minified.dot.txt](https://github.com/joernio/joern/files/10086159/ddg-minified.dot.txt)

**Comment by bbrehm** [comment]
I think this is a question of what people mean with ddg?

Cursory googling reveals two conflicting definitions that appear to be in common use.

That is, consider the program
```
void foo(int* x){
print(*x);
*x = 0;
}
```
Following e.g. https://home.cs.colorado.edu/~kena/classes/5828/s99/lectures/lecture25.pdf slide 19, the first statement (the memory load) and the second (the memory store) would have a data dependency from load to store (basically because the two statements cannot be reordered). Following that definition, you would expect a dependency in your example.

Following instead the definition in https://compilers.cs.uni-saarland.de/teaching/spa/2014/slides/ProgramDependenceGraph.pdf slide 12, there is no data dependence: The two statements cannot affect each other (and the superscalar CPU can execute them in parallel). Following that definition, you would expect no dependency in your program.

So I guess this is a documentation issue?

I don't know, I am a mathematician, not a computer scientist. I don't particularly care about official definitions, we just should be clear in the docs what we compute.

FWIW, I think the concept that has no data dependencies here is much more useful, because it behaves pretty well under SSA and mem2reg like compiler transforms; nobody cares whether you can reorder lines of code, the question is what dependencies the CPU sees and which ones it can kill via register renaming.

**Review by bbrehm — APPROVED** [review]
From my point of view, we could merge this. What do you think @max-leuthaeuser @mpollmeier ?

**Comment by mpollmeier** [comment]
Sounds good to me - certainly better and clearer than before, thanks @bbrehm 
As discussed on discord, hopefully @fabsx00 can add some more clarity and direction, once he's back.

**Comment by max-leuthaeuser** [comment]
Looks good, thanks!

**Pull request merged**
