### PR TITLE
Fix for wrong identifier names

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
Fixes: https://github.com/joernio/joern/issues/1326

Also: we do not need to run system header file auto discovery during tests. Just wasting time there.

### CODE REVIEW

**Comment by max-leuthaeuser** [comment]
@fabsx00 @mpollmeier 
I think there is something broken within the php installation stuff:

```
Run joern-cli/frontends/php2cpg/installdeps.sh
Installer corrupt
Could not open input file: composer-setup.php
PHP Warning:  unlink(composer-setup.php): No such file or directory in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. unlink($filename = 'composer-setup.php') Command line code:1
Could not open input file: composer.phar
```

Other PR runs here also failed because of this.

**Comment by mpollmeier** [comment]
Yeah that looks like a github-actions issue... I'll look into it, hopefully today.

**Comment by ursachec** [comment]
@mpollmeier @max-leuthaeuser this will pbb fix it https://github.com/joernio/joern/pull/1331/files
talked to @fabsx00 offline, it looks like we need to follow the recommendation of their docs and fetch the installer automatically https://github.com/joernio/joern/issues/1332
if bumping the PHP composer install script checksum becomes too annoying, we can also disable it temporarily

**Comment by ursachec** [comment]
looks like that did it. @max-leuthaeuser if you rebase this PR from master, tests should run again

**Comment by mpollmeier** [comment]
warning @max-leuthaeuser i rebased and force-pushed this branch. all green now

**Comment by max-leuthaeuser** [comment]
Thanks!

**Review by fabsx00 — APPROVED** [review]

**Pull request merged**
