### PR TITLE
rubysrc2cpg: refactoring astForAliasStatement

### PR DESCRIPTION
**Pull request by xavierpinho**

### CODE REVIEW

**Comment by ursachec** [comment]
I'm not familiar with Ruby's syntax, and I don't know if you already had a conversation with someone about how best to represent aliases - but on a first glance, I'd say that the frontend should create an ast for the alias (e.g. a method stub if that works)

**Review by ursachec — APPROVED** [review]
:+1: on the refactoring

**Comment by xavierpinho** [comment]
Oh absolutely - just discussing that with @rahul-privado. The plan is: place `alias` statements in the AST and have a pass later on replacing aliased method call fullnames respectively. Right now, the resolving is done during the AST which can be a mess.

**Comment by ursachec** [comment]
@xavierpinho I'm just throwing ideas out there - but I think it might be possible to remove the need for a separate pass if you stub a method for the alias for which its body consists of a single expression - a call of the original method.

**Comment by xavierpinho** [comment]
> @xavierpinho I'm just throwing ideas out there - but I think it might be possible to remove the need for a separate pass if you stub a method for the alias for which its body consists of a single expression - a call of the original method.

That would be neat, yes! Thanks for the suggestion :) Alas, `undef` is a party pooper:
```ruby
def myMethod(arg); puts arg; end
alias :myAlias :myMethod
myAlias(0) # works
undef :myAlias
myAlias(0) # doesn't work anymore
```
But this is just semantics: hopefully snippets like these are not common!

**Comment by xavierpinho** [comment]
Good stuff! 👍 I think it's worth trying that first, for sure :)

**Pull request merged**
