### PR TITLE
Revert "jssrc2cpg: Handle Destructured Params (#2883)"

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
This reverts commit b5336999a69a25cccc69531629af660e263d9999.

@DavidBakerEffendi Had to revert this as it creates identifier nodes not being included into the AST. That crashes many passes later on. Check e.g., tarpit-nodejs

### CODE REVIEW

**Comment by max-leuthaeuser** [comment]
@DavidBakerEffendi There is also another problem with some of your recent changes:
On tarpit-nodejs again:
```
joern> cpg.method.whereNot(_._astIn).size
res5: Int = 46
```
Could you checkt this and maybe push a fix directly at this PR here?

**Comment by DavidBakerEffendi** [comment]
@max-leuthaeuser thanks, will do, I'll also see if I can create a unit test from that project to reproduce with.

**Review by maltek — APPROVED** [review]

**Comment by DavidBakerEffendi** [comment]
FYI looking into this today

**Comment by DavidBakerEffendi** [comment]
@max-leuthaeuser decided [to do it in my own PR](https://github.com/joernio/joern/pull/2979) since it was a 2 line fix, then added 2 lines of tests to verify it

**Comment by DavidBakerEffendi** [comment]
> @max-leuthaeuser decided [to do it in my own PR](https://github.com/joernio/joern/pull/2979) since it was a 2 line fix, then added 2 lines of tests to verify it

Then again, whether this doesn't create an invalid CPG is another question lol, but it seems fine with the bit of querying I did with the resulting CPGs

**Comment by DavidBakerEffendi** [comment]
Described bug resolved by https://github.com/joernio/joern/pull/2979

**Pull request closed without merging**
