### PR TITLE
A call linker for python

### PR DESCRIPTION
**Pull request by Liyw979**
This PR introduce a call linker for python.
The linker links ```calls``` and ```methods``` only by their **name**(not full name), because it's hard to decide thier full name in a dynamic language.
Though this will result in wrong edges, it will make interprocedural data flow analysis work for the moment.

### CODE REVIEW

**Review by fabsx00 — APPROVED** [review]
Ok, sure, let's do this for now. It's better than not having CALL edges at all.

**Comment by Liyw979** [comment]
Let me resolve the conflicts

**Comment by fabsx00** [comment]
Cool, thanks.

**Comment by Liyw979** [comment]
Actually, I think this linker can also be used for ```js``` and ```php``` for the moment.
By the way, please review #1847

**Pull request merged**
