### PR TITLE
Restructure dependency resolver test suite

### PR DESCRIPTION
**Pull request by ursachec**
Without this change, IntelliJ 2021.3.2 does not detect individual test
cases, which makes them annoying to run individually.

### CODE REVIEW

**Review by max-leuthaeuser — APPROVED** [review]

**Review by mpollmeier — COMMENTED** [review]
I'm a bit confused, the changes look like this is related to the github actions windows runner, but the PR description mentions intellij.

If it's the latter, then https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/codepropertygraph/src/main/scala/io/shiftleft/utils/ProjectRoot.scala could help - it's used in other tests in the joern build already, and works around the issue that intellij and sbt use different root dirs for their tests.

**Comment by ursachec** [comment]
Agrred offline with @mpollmeier that his concerns were unfounded, incorrect, and just a waste of everyone's time.

**Comment by mpollmeier** [comment]
😡 👿 😠

**Comment by ursachec** [comment]
`¯\_(ツ)_/¯` Te lo hiciste a ti mismo, señor.

**Comment by mpollmeier** [comment]
no he hecho nada 👼🏻

**Comment by ursachec** [comment]
:hugs:

**Pull request merged**
