### PR TITLE
[c#] Implements the `forAst` Construct

### PR DESCRIPTION
**Pull request by DavidBakerEffendi**
The current `foreach` implementation is based on an older approach that doesn't capture the semantics quite as well.

This PR implements the newer `forAst` construct, which encourages de-sugaring and representing what is semantically happening underneath the `foreach` statement.

Resolves https://github.com/joernio/joern/issues/4674#issuecomment-2222254060

### CODE REVIEW

**Review by AndreiDreyer — APPROVED** [review]

**Comment by chengkenyong** [comment]
Hi!  @DavidBakerEffendi ,Thank you very much for solving my problem! Actually, I also made some rough modifications to the foreach beforehand. The specific modifications are as follows. 
```scala 
  private def astForForEachStatement(forEachStmt: DotNetNodeInfo): Seq[Ast] = {
    val forEachNode     = controlStructureNode(forEachStmt, ControlStructureTypes.FOR, forEachStmt.code)
    val iterableAst     = astForNode(forEachStmt.json(ParserKeys.Expression))

    // ----------------------------------Add the foreach iterator variable to the previous scope-------------------------------------
    val identifierValue = forEachStmt.json(ParserKeys.Identifier)(ParserKeys.Value).str
    val _localNode =
      localNode(
        node = createDotNetNodeInfo(forEachStmt.json(ParserKeys.Type)),
        name = identifierValue,
        code = identifierValue,
        typeFullName = nodeTypeFullName(createDotNetNodeInfo(forEachStmt.json(ParserKeys.Type)))
      )
    scope.addToScope(identifierValue, _localNode)
    // -----------------------------------------------------------------------------------------------------------------

    val forEachBlockAst = astForBlock(createDotNetNodeInfo(forEachStmt.json(ParserKeys.Statement)))

    val _identifierNode =
      identifierNode(
        node = createDotNetNodeInfo(forEachStmt.json(ParserKeys.Type)),
        name = identifierValue,
        code = identifierValue,
        typeFullName = nodeTypeFullName(createDotNetNodeInfo(forEachStmt.json(ParserKeys.Type)))
      )
    val iteratorVarAst = Ast(_identifierNode)

    // ------------------------------------------ Define a custom "in" operator--------------------------------------------------
    val args         = iteratorVarAst +: iterableAst
    val iterableCode = forEachStmt.json(ParserKeys.Expression)(ParserKeys.MetaData)(ParserKeys.Code).str
    val operatorCode = s"$identifierValue in $iterableCode"
    val operatorAst = callNode(
      forEachStmt,
      operatorCode,
      "<operator>.elementOf",
      "<operator>.elementOf",
      DispatchTypes.STATIC_DISPATCH,
      None,
      Option(_identifierNode.typeFullName)
    )
    val conditionAst = Seq(callAst(operatorAst, args))
    scope.moveToScope(identifierValue)//Remove identifierValue from the scope
    // -----------------------------------------------------------------------------------------------------------------

    Seq(
      Ast(forEachNode)
        .withChildren(conditionAst)
        .withChild(forEachBlockAst)
        .withConditionEdges(forEachNode, conditionAst.flatMap(_.root).toList)
    )
  }
```

However, during testing, I encountered many minor issues. For example, in the test code sample below, 
微信截图_20240829153939
there are data flow directions that violate the control flow.
graphviz (9)
 But when I tested your submitted code, I found that these issues didn't exist. I'm very curious about the reason behind this (I was actually looking into the specific CFG implementation logic in Joern). I would be very grateful if you could explain this to me.

**Comment by DavidBakerEffendi** [comment]
Hi @chengkenyong, so while your implementation is quite close, one thing to keep in mind that unknown calls are overapproximated by Joern, and I think that may be what is causing the extra unrealizable paths. If a call is unknown, and doesn't have a respective semantic entry, it will consider all input and output arguments being defined and used by all input and outpu arguments. By adding `<operator>.elementOf` without specifying its semantic under `DefaultSemantics` (under the `dataflowengineoss` module) it may cause this. 

Another cause may be how the CFG generator interprets children on the `FOR` control structures, where each position has a special meaning in the scope of where the control flows (which then may result in data-flows being correct or incorrect).

**Comment by chengkenyong** [comment]
Hi @DavidBakerEffendi ,I really appreciate your answer! Actually, I have already specified the semantics for <operator>.elementOf under the dataflowengineoss module, but the results are not ideal. Currently, I'm also looking into the logic of adding control flow edges to child nodes in the cfgForForStatements method in the CFG!Your suggestion has further clarified my direction.Thanks

**Comment by DavidBakerEffendi** [comment]
@chengkenyong This is quite unusual, I wonder if this is caused by how field sources are retrieved at the start of the data-flow analysis. I know we've had to do some workarounds for handling global variables in dynamic languages on file-level, so that might be the cause. The code I'm thinking about is under `io.joern.dataflowengineoss.queryengine.SourcesToStartingPoints`

**Comment by chengkenyong** [comment]
@DavidBakerEffendi , Thank you very much for your explanation. I will take a look at its implementation logic.

**Pull request merged**
