### PR TITLE
Fix pending dataflow test case in C

### PR DESCRIPTION
**Pull request by Liyw979**
With ```EngineContext(config = EngineConfig(maxCallDepth = 4))``` 😂

### CODE REVIEW

**Comment by Liyw979** [comment]
By the way, can you provide way to set ```maxCallDepth``` in the ```joern console``` since the default ```maxCallDepth``` is ```2```

image

**Comment by fabsx00** [comment]
`maxCallDepth` is a `var`, so, on the shell, you can issue the following:
```
context.config.maxCallDepth = 4
```

**Comment by fabsx00** [comment]
Makes me wonder whether we should increase the default value of `maxCallDepth` as well. Otherwise, tests pass but the flows aren't found in practice.

**Comment by Liyw979** [comment]
Sounds good. It takes me one month to find out there is such a configuration of dataflow algrithm.

**Comment by fabsx00** [comment]
This one changes the default value to 4, so, on this PR, you can omit the `=4`:
https://github.com/joernio/joern/pull/1841

**Comment by Liyw979** [comment]
@fabsx00 How about leaving this PR unchanged and create a new PR the clean up ```EngineConfig(maxCallDepth = 4)``` in all test fixtures.
image

**Comment by fabsx00** [comment]
Fine with me as well.

**Pull request merged**
