### PR TITLE
c2cpg: re-added modifier to code field of local

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
This is for: https://github.com/joernio/joern/issues/1256

### CODE REVIEW

**Comment by max-leuthaeuser** [comment]
Hm, `CPGQLServerTests` fail on Windows with, e.g.,:

```
[info] - should allow posting a simple query without any websocket connections established *** FAILED ***
[info]   requests.RequestFailedException: Request to http://localhost:8081/query failed with status code 400
[info] Unable to deserialize input JSON text: java.lang.NoClassDefFoundError: Could not initialize class org.xnio.channels.Channels
[info] java.lang.NoClassDefFoundError: Could not initialize class org.xnio.channels.Channels
[info] 	at io.undertow.io.UndertowInputStream.readIntoBuffer(UndertowInputStream.java:109)
[info] 	at io.undertow.io.UndertowInputStream.read(UndertowInputStream.java:89)
[info] 	at io.undertow.io.UndertowInputStream.read(UndertowInputStream.java:78)
[info] 	at cask.internal.Util$.transferTo(Util.scala:51)
[info] 	at cask.endpoints.postJson.wrapFunction(JsonEndpoint.scala:54)
[info] 	at cask.router.Decorator$.invoke(Decorators.scala:52)
[info] 	at cask.router.Decorator$.$anonfun$invoke$1(Decorators.scala:47)
[info] 	at io.joern.console.cpgqlserver.WebServiceWithWebSocket$basicAuth.wrapFunction(CPGQLServer.scala:77)
[info] 	at cask.router.Decorator$.invoke(Decorators.scala:47)
[info] 	at cask.main.Main$DefaultHandler.handleRequest(Main.scala:115)
[info] 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
[info] 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
[info] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[info] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
[info] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
[info] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1423)
[info] 	at java.base/java.lang.Thread.run(Thread.java:829)
[info]   at requests.Requester$$anon$1.readBytesThrough(Requester.scala:359)
[info]   at geny.Readable.writeBytesTo(Writable.scala:93)
[info]   at geny.Readable.writeBytesTo$(Writable.scala:93)
[info]   at requests.Requester$$anon$1.writeBytesTo(Requester.scala:165)
[info]   at requests.Requester.apply(Requester.scala:114)
[info]   at io.joern.console.cpgqlserver.CPGQLServerTests.postQuery(CPGQLServerTests.scala:24)
[info]   at io.joern.console.cpgqlserver.CPGQLServerTests.$anonfun$new$5(CPGQLServerTests.scala:55)
[info]   at io.joern.console.cpgqlserver.Fixture$.apply(CPGQLServerTests.scala:330)
[info]   at io.joern.console.cpgqlserver.CPGQLServerTests.$anonfun$new$4(CPGQLServerTests.scala:54)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   ...
```
This PR does not touch anything there. 
@mpollmeier Any idea?

**Comment by mpollmeier** [comment]
I assume it's due to the warning just above that error, which only occurs in the windows build:
```
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
```

I'll try something out and will push directly to this branch.

**Comment by mpollmeier** [comment]
This doesn't quite make sense, including how your changes would lead to this issue popping up now... I'll try to revitalise some old windows vm to reproduce, and debug this in a separate PR.

**Comment by mpollmeier** [comment]
Different PR, same issue:
https://github.com/joernio/joern/pull/1284

**Comment by mpollmeier** [comment]
debug PR: https://github.com/joernio/joern/pull/1283
this also happens with windows 2022

**Comment by mpollmeier** [comment]
windows build isssue is resolved now

**Review by mpollmeier — APPROVED** [review]

**Pull request merged**
